Add sid command
encryptededdy/intestinebot pull request #4
Opened 2018-11-13 03:52 UTC by mkem114

Sid command prepends a message with a vulgar message

2018-11-13 03:56 UTC, encryptededdy requested changes

2018-11-13 03:56 UTC, encryptededdy commented on eddybot.php
> +            apiRequestWebhook("sendMessage", array('chat_id' => $chat_id, "text" => "Lol shut the fuck up u idiot fuck stupid dumb" . $fullwidth));
Wouldn't $fullwidth be undefined? Also should add a space at the end.

2018-11-13 19:47 UTC, mkem114 commented on eddybot.php
> +            apiRequestWebhook("sendMessage", array('chat_id' => $chat_id, "text" => "Lol shut the fuck up u idiot fuck stupid dumb" . $fullwidth));
Apologies will change to $text.

Just wondering if removing the first four characters would leave the space after the "/sid"?

2018-11-14 00:13 UTC, mkem114 commented on eddybot.php
> +            apiRequestWebhook("sendMessage", array('chat_id' => $chat_id, "text" => "Lol shut the fuck up u idiot fuck stupid dumb" . $fullwidth));
A discussion came to the conclusion that removing only four characters will solve the space problem.

2018-11-14 04:48 UTC, encryptededdy approved these changes

2018-11-14 04:48 UTC, merged